config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'
    resources :articles do
    	resources :comments
    end
    resources :tags
    resources :authors
    resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:name)}
		self.tags = new_or_found_tags
	end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
	validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save
		flash.notice = "Straipsnis '#{@article.title}' Sukurtas!"
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash.notice = "Straipsnis '#{@article.title}' Ištrintas!"
		redirect_to articles_path
	end

	def edit 
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		flash.notice = "Straipsnis '#{@article.title}' Atnaujintas!"
		redirect_to article_path(@article)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
	end

    def create
	    if login(params[:email], params[:password])
	      redirect_back_or_to(articles_path, notice: 'Prisijungta sėkmingai.')
	    else
	      flash.now.alert = "Nepavyko prisijunkti."
	      render action: :new
	    end
	end

	def destroy
		logout
		redirect_to(:authors, notice: 'Atsijungta!')
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Autorius sėkmingai sukurtas.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Autorius sėkmingai atnaujintas.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Autorius sėkmingai ištrintas.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save
		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]
	
	def show
		@tag = Tag.find(params[:id])
	end

	def index
		@tags = Tag.all
	end

	def destroy 
		@tag = Tag.find(params[:id])
		@tag.destroy
		flash.notice = "Etiketė '#{@tag}' Ištrinta!"
		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4><%= comment.author_name %> komentaras</h4>
  <p>Sukurtas <%= comment.created_at.getlocal.strftime("%Y/%m/%d %H:%M") %> </p>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title, "Pavadinimas" %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, "Tekstas" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url, class: 'image-small' %><br/>
  <% end %>
  <%= f.label :image, "Prideti vaizdą" %><br />
  <%= f.file_field :image %>
</p>

  <p>
    <%= f.submit 'Atnaujinti', class: 'btn'%>
  </p>
  <p>
  <%= f.label :tag_list, "Etiketės" %><br />
  <%= f.text_field :tag_list %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Redaguok Straipsnį</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>Visi Straipsniai</h1>

<ul class="articles">
	<% @articles.each do |article| %>
		<li class="article">
			<%= link_to article.title, article_path(article) %>
		</li>
	<% end %>
</ul>

app/views/articles/new.html.erb
<h1>Sukurk Naują Straipsnį</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	Etiketės:
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
<% if @article.image.exists? %>
	<p><%= image_tag @article.image.url, class: 'image-medium' %></p>
<% end %>
<p><%= @article.body %></p>
<hr>
<h3>Komentarai (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<hr>
<%= render partial: 'comments/form' %>
<hr>
<%= link_to "<< Atgal į straipsnių sąrašą", articles_path %>
<% if logged_in? %>
	<%= link_to "Redaguoti ", edit_article_path(@article) %>
	<%= link_to "Ištrinti", article_path(@article), method: :delete, data: {confirm: "Ar tikrai ištrinti straipsnį?"} %>
<% end %>

app/views/author_sessions/new.html.erb
<h1>Prisijungimas</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <p>
    <%= label_tag :email, "Elektroninis Paštas" %><br />
    <%= text_field_tag :email %>
  </p>
  <p>
    <%= label_tag :password, "Slaptažodis" %><br />
    <%= password_field_tag :password %>
  </p>
  <p>
    <%= submit_tag "Prisijunk", class: 'btn' %>
  </p>
<% end %>

<%= link_to '<< Atgal', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username, "Vardas" %></br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email, "Elektroninis Paštas" %></br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password, "Slaptažodis" %></br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, "Slaptažodžio Patvirtinimas" %></br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit 'Siųsti', class: 'btn'%>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Redagavimas</h1>

<%= render 'form', author: @author %>

<%= link_to '<< Atgal', authors_path %> |
<%= link_to 'Rodyti', @author %>

app/views/authors/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Autoriai</h1>

<table>
  <thead>
    <tr>
      <th>Vardas</th>
      <th>El. Paštas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Rodyti', author %></td>
        <td><%= link_to 'Redaguoti', edit_author_path(author) %></td>
        <td><%= link_to 'Ištrinti', author, method: :delete, data: { confirm: 'Ar esi tikrai nori ištrinti autorių?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Naujas Autorius', new_author_path %>

app/views/authors/new.html.erb
<h1>Naujas Autorius</h1>

<%= render 'form', author: @author %>

<%= link_to '<< Atgal', authors_path %>

app/views/authors/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Vardas:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>El. Paštas:</strong>
  <%= @author.email %>
</p>

<%= link_to '<< Atgal', authors_path %> |
<%= link_to 'Redaguoti', edit_author_path(@author) %> 

app/views/comments/_form.html.erb
<h3>Rašyk Komentarą</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Tavo Vardas" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Tavo Komentaras" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Komentuoti', class: 'btn' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails blogas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald:300,400|Roboto:100,300,400&subset=latin-ext" rel="stylesheet"> 
  </head>

  <body>
    
<div class="container">
      <div class="header">
        <h1 class="header-heading">RAILS</h1>
      </div>

      <div class="nav-bar">
        <ul class="nav">
          <li><%= link_to "Straipsniai", articles_path %></li>
          <li><%= link_to "Antraštės", tags_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Naujas", new_article_path %></li>
          <% end %>
          
        </ul>
      </div>

      <div class="content">
      <p class="flash"><%= flash.notice %></p>
      <h6>
        <% if logged_in? %>
          <%= "#{current_user.email}" %>
          <%= link_to "| Atsijunk", logout_path %>
        <% else %>
          <%= link_to "Prisijunk", login_path %>
        <% end %>
      </h6><hr>
      <!-- <hr> -->
        <%= yield %>
      </div>

      <div class="footer">
        &copy; Copyright 2016
      </div></div>
    
  </body>
</html>

app/views/tags/index.html.erb
<h1>Visos Etiketės</h1>

<ul id="tags">
	<% @tags.each do |tag| %>
		<li class="tag"><%= link_to tag, tag_path(tag) %></li>
		<% if logged_in? %>
			<%= link_to "ištrinti", tag_path(tag), method: :delete %>
		<% end %>
	<% end %>
</ul>

<hr></hr>
<%= link_to "<< Atgal į straipsnių sąrašą", articles_path %>

app/views/tags/show.html.erb
<h1>Straipsniai su <%= @tag.name %> etikete</h1>

<ul>
	<% @tag.articles.each do |article| %>
		<li class="article"><%= link_to article.title, article_path(article) %></li>
	<% end %>
	
</ul>